### ISSUE TITLE
Cannot run frameit. Fails on Trim method

### ISSUE THREAD

**Issue by osgafarov** [fastlane/frameit#24]
Hi

When I run frameit I am getting the following error:
```
/Users/username/.rvm/gems/ruby-2.2.1@global/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:382:in `block in method_missing': undefined method `trim' for #<MiniMagick::Image:0x007f94de36dfd8> (NoMethodError)
```

Can you check it please?
Thanks

**Comment by KrauseFx** [comment]
Which version of `imagemagick` do you have installed? Did you use `homebrew` to install it?

**Comment by osgafarov** [comment]
Version: imagemagick-6.9.1-4
Installed using homebrew.

**Comment by KrauseFx** [comment]
Could you try the latest version of `frameit` and let me know if that works for you?
