### ISSUE TITLE
Unsupported screen size [1324, 895]

### ISSUE THREAD

**Issue by walsht** [fastlane/frameit#30]
Getting a Unsupported screen size on running frameit and pushing to iTunes Connect.

I am only getting this for frameit images that do not have text.  Is text required?
 
[06:46:01]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/deliver-0.12.1/lib/deliver/app_screenshot.rb:126:in `calculate_screen_size': Unsupported screen size [1324, 895] for path '/Users/twalsh/Documents/Projects/...

**Comment by KrauseFx** [comment]
Did you use `frameit` to add device frames around your screenshots, but no title? If so, that's because it doesn't match the iTC requirements. If you share a bit more of your setup and what you want to achieve I can help you :

**Comment by walsht** [comment]
I am trying to add frameit with text for all my screenshots, but found it will not work for Chinese Characters.  So, looking to just use the frameit without text.  That is when I get the error above.

**Comment by ZaneH** [comment]
I'm also getting this error when not adding text. I just want to use the device frames without titles.

**Comment by osrl** [comment]
+1 to @ZaneH 
I just frame the snapshots with `frameit(white: true, path: './fastlane/screenshots')` Here is the log (error number e9ff75535b7ff3f321486d9aeb55f523):

```
/usr/local/lib/ruby/gems/2.2.0/gems/deliver-1.9.0/lib/deliver/app_screenshot.rb:165:in `calculate_screen_size': [!] Unsupported screen size [645, 1364] for path '/Users/osrl/Documents/XCodeworkspace/Swift/Oris Gezgin/fastlane/screenshots/tr/iPhone5-01MainScreen_framed.png' (RuntimeError)

Isn't frameit intended to match the iTC requirements?
