### ISSUE TITLE
StringParser didn't work when using UTF-8 encoded title.strings file.

### ISSUE THREAD

**Issue by ntaku** [fastlane/frameit#32]
Thank you for providing such a nice tool. I tried to create screenshots with title and it was failed. This is the error message.

```
[22:06:30]: Could not get title for screenshot ./en-US/Brainstorming.png. Please provide one in your Framefile.json
```

This was caused by UTF-8 encoded title.strings file, so I can avoid this error by creating title.strings by UTF-16. I thinks this line caused this problem.

strings_parser.rb L11
```
# A .strings file is UTF-16 encoded. We only want to deal with UTF-8
content = `iconv -f UTF-16 -t UTF-8 '#{path}'`
```

**Comment by KrauseFx** [comment]
`.strings` files should always be UTF-16. Have you created them in UTF-8? If so, I think `frameit` should detect this and show a proper error message. What do you think?

**Comment by ntaku** [comment]
I created .strings files in UTF-8 because I didn't know .strings files should always be UTF-16. I appreciate if frameit tell this by error message.

**Comment by voisine** [comment]
strings files are UTF-16 by default, but UTF-8 works just fine inside iOS projects, why not handle both?

**Comment by KrauseFx** [comment]
@voisine agreed, `frameit` should just handle both formats.

**Comment by ide** [comment]
Ran into this too. This library looks like it could help with the charset detection and conversion: https://github.com/brianmario/charlock_holmes

**Comment by kmayoral** [comment]
Note, if you're creating your title.strings and keywords.strings files in Sublime Text, you'll need to save them as UTF-16 BE as the little endian option is not recognized by frameit either.
