### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by ryanjm** [fastlane/frameit#34]
Instead of referencing a background image it'd be great to be able to give it a hex color for a solid background.

**Comment by tabrindle** [comment]
+1

**Comment by KrauseFx** [comment]
Sounds good :+1:

**Comment by guidev** [comment]
+1

**Comment by guidev** [comment]
A little workaround: I used a small background.png (100px * 100px) with a solid color and it works well.

**Comment by rodericj** [comment]
And if you are a newb like me, this might help:

`convert -size 100x100 xc:#1F3A93 background.jpg`

That'll create a solid color background that is 100x100 at the color #1f3a93.

**Comment by Tibbs** [comment]
+1
