### ISSUE TITLE
Documentation for Framefile.json

### ISSUE THREAD

**Issue by ryanjm** [fastlane/frameit#35]
It'd be helpful to have some documentation around `Framefile.json`. What is required, what is optional?

I'm trying to just have a title and no keyword, but I'm not getting it to work yet.

**Comment by guidev** [comment]
+1

**Comment by olutsenko** [comment]
Is it possible to get only a title with no keyword?

**Comment by KrauseFx** [comment]
@olutsenko Yes, just don't specify a keyword.

**Comment by olutsenko** [comment]
@KrauseFx Hi Felix, thanks a lot for you reply. I have a problem setting the title. Get this error:

*Could not get title for screenshot ./Brainstorming.png. Please provide one in your Framefile.json*

What is the format for specifying title? I already have folder en-US with title.strings with a few strings. This doesn't seem to help.

**Comment by KrauseFx** [comment]
@olutsenko Please share your existing configuration, so I can tell you why it isn't working :+1:

**Comment by olutsenko** [comment]
Basically I am trying to get example to work.

**Framefile.json**

{
    "default": {
        "keyword": {
            "font": "./fonts/SF-UI-Display-Regular.otf"
        },
        "title": {
            "font": "./fonts/SF-UI-Display-Regular.otf",
            "color": "#545454"
        },
        "background": "./background.jpg",
        "padding": 50
    },
    
    "data": [
             {
             "filter": "Brainstorming",
             "keyword": {
             "color": "#d21559"
             }
             },
             {
             "filter": "Organizing",
             "keyword": {
             "color": "#feb909"
             }
             }
             ]
}


**title.strings**

"Brainstorming" = "Let Your Ideas Grow";
"Organizing" = "Think Content, Not Layout";

**keyword.strings**
"Brainstorming" = "BRAINSTORMING";
"Organizing" = "ORGANIZING";

**Output**

$ frameit
[18:49:28]: Could not get title for screenshot ./Brainstorming.png. Please provide one in your Framefile.json
[18:49:32]: Could not get title for screenshot ./Organizing.png. Please provide one in your Framefile.json

**Comment by KrauseFx** [comment]
@olutsenko Remove the `filter` elements from your `Framefile.json`, they are used to only apply a rule for certain files.

**Comment by olutsenko** [comment]
{
    "default": {
        "keyword": {
            "font": "./fonts/SF-UI-Display-Regular.otf",
            "supported": ["en-US"]
        },
        "title": {
            "font": "./fonts/SF-UI-Display-Regular.otf",
            "supported": ["en-US"],
            "color": "#545454"
        },
        "background": "./background.jpg",
        "padding": 50
    },
    
    "data": [
             {
             "keyword": {
             "color": "#d21559"
             }
             },
             {
             "keyword": {
             "color": "#feb909"
             }
             }
             ]
}

**Output:**

$ frameit
[18:57:37]: no implicit conversion of nil into String
[18:57:40]: no implicit conversion of nil into String

**Comment by KrauseFx** [comment]
@olutsenko Could you submit a separate issue (as we're going off-topic here) and share your complete output when running `frameit`? Without the stack trace it's hard to guess the reason for the error.

**Comment by ayushgoel** [comment]
+1

**Comment by paulshapiro** [comment]
+1

**Comment by aabulkhairov** [comment]
Is there any progress on this?
Me too encountering both

    Could not get title for screenshot ./Brainstorming.png. Please provide one in your Framefile.json

and 

    no implicit conversion of nil into String

**Comment by i2amsam** [comment]
@aabulkhairov could you open another issue with the full output of running the command and your `Framefile.json`
