### ISSUE TITLE
Can not generate a framed screen with a title.

### ISSUE THREAD

**Issue by olutsenko** [fastlane/frameit#49]
Hello,

I am trying to get the example working. I want to have two screenshots framed with a title on top. Bellow is my configuration + output for the 'frameit --verbose'

<img width="541" alt="screenshot 2015-09-18 08 46 47" src="https://cloud.githubusercontent.com/assets/303121/9953531/e38abdc6-5de1-11e5-9a27-00c3980912b8.png">

**Framefile.json**
```
{
    "default": {
        "keyword": {
            "font": "./fonts/SF-UI-Display-Regular.otf",
            "supported": ["en-US"]
        },
        "title": {
            "font": "./fonts/SF-UI-Display-Regular.otf",
            "supported": ["en-US"],
            "color": "#545454"
        },
        "background": "./background.jpg",
        "padding": 50
    },
    
    "data": [
             {
             "keyword": {
             "color": "#d21559"
             }
             },
             {
             "keyword": {
             "color": "#feb909"
             }
             }
             ]
}
```

**title.strings**
```
"Brainstorming" = "Let Your Ideas Grow";
"Organizing" = "Think Content, Not Layout";

**keyword.strings**
"Brainstorming" = "BRAINSTORMING";
"Organizing" = "ORGANIZING";
```

**Output**
```
$ frameit --verbose
INFO [2015-09-18 08:44:19.03]: Parsing config file '/Users/oleg/Desktop/test/Framefile.json'
ERROR [2015-09-18 08:44:19.03]: no implicit conversion of nil into String
ERROR [2015-09-18 08:44:19.03]: Backtrace:
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/config_parser.rb:27:in `include?'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/config_parser.rb:27:in `block in fetch_value'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/config_parser.rb:27:in `each'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/config_parser.rb:27:in `find'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/config_parser.rb:27:in `fetch_value'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:252:in `fetch_config'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:83:in `should_add_title?'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:16:in `frame!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/screenshot.rb:72:in `frame!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:29:in `block in run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:21:in `each'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:21:in `run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:31:in `block (2 levels) in run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:55:in `run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:63:in `<top (required)>'
	/usr/bin/frameit:23:in `load'
	/usr/bin/frameit:23:in `<main>'
INFO [2015-09-18 08:44:21.42]: Parsing config file '/Users/oleg/Desktop/test/Framefile.json'
ERROR [2015-09-18 08:44:21.42]: no implicit conversion of nil into String
ERROR [2015-09-18 08:44:21.42]: Backtrace:
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/config_parser.rb:27:in `include?'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/config_parser.rb:27:in `block in fetch_value'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/config_parser.rb:27:in `each'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/config_parser.rb:27:in `find'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/config_parser.rb:27:in `fetch_value'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:252:in `fetch_config'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:83:in `should_add_title?'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:16:in `frame!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/screenshot.rb:72:in `frame!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:29:in `block in run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:21:in `each'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:21:in `run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:31:in `block (2 levels) in run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:55:in `run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:63:in `<top (required)>'
	/usr/bin/frameit:23:in `load'
	/usr/bin/frameit:23:in `<main>'
```

**Comment by skrew** [comment]
Had the same problem, you can try:
- Use the same example, like you do in precedent issue.
- Open files in Xcode (title.strings and keyword.strings) and in right panel, under "text settings", change text settings to "Unicode (UTF-16)"

Works for me only where files are encoded in UTF-16.

I'm happy now ! ;)

**Comment by olutsenko** [comment]
@skrew Thanks a lot for your reply. Unfortunately your suggestion didn't solve the issue. Output is the same.

**Comment by skrew** [comment]
@olutsenko add "filter" in "data" in Framefile.json (like MindNode example)

**Comment by olutsenko** [comment]
It looks like it doesn't go into 'en-US' folder to read the .strings file. Because of that it falls back to default title which must be specified in .json file. But what format for specifying the title?

I tried one bellow, but result is the same.

 "data": [
             {
             "filter": "Brainstorming",
             "title": "Test title",
             "keyword": {
             "color": "#d21559"
             }
...

Output:

$ frameit --verbose
INFO [2015-09-20 13:04:44.39]: Parsing config file '/Users/oleg/Desktop/test/Framefile.json'
DEBUG [2015-09-20 13:04:45.55]: Falling back to default text as there was nothing specified in the .strings file
DEBUG [2015-09-20 13:04:45.55]: Falling back to default text as there was nothing specified in the .strings file
ERROR [2015-09-20 13:04:45.55]: Could not get title for screenshot ./en-US-Brainstorming.png. Please provide one in your Framefile.json
ERROR [2015-09-20 13:04:45.55]: Backtrace:
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:273:in `fetch_text'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:211:in `block in build_title_images'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:211:in `keep_if'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:211:in `build_title_images'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:156:in `add_title'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:102:in `complex_framing'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:17:in `frame!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/screenshot.rb:72:in `frame!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:29:in `block in run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:21:in `each'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:21:in `run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:31:in `block (2 levels) in run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:55:in `run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:63:in `<top (required)>'
	/usr/bin/frameit:23:in `load'
	/usr/bin/frameit:23:in `<main>'
INFO [2015-09-20 13:04:47.40]: Parsing config file '/Users/oleg/Desktop/test/Framefile.json'
DEBUG [2015-09-20 13:04:48.57]: Falling back to default text as there was nothing specified in the .strings file
DEBUG [2015-09-20 13:04:48.57]: Falling back to default text as there was nothing specified in the .strings file
ERROR [2015-09-20 13:04:48.57]: Could not get title for screenshot ./en-US-Organizing.png. Please provide one in your Framefile.json
ERROR [2015-09-20 13:04:48.57]: Backtrace:
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:273:in `fetch_text'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:211:in `block in build_title_images'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:211:in `keep_if'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:211:in `build_title_images'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:156:in `add_title'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:102:in `complex_framing'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/editor.rb:17:in `frame!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/screenshot.rb:72:in `frame!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:29:in `block in run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:21:in `each'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/lib/frameit/runner.rb:21:in `run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:31:in `block (2 levels) in run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:55:in `run'
	/Library/Ruby/Gems/2.0.0/gems/frameit-2.2.1/bin/frameit:63:in `<top (required)>'
	/usr/bin/frameit:23:in `load'
	/usr/bin/frameit:23:in `<main>'

**Comment by skrew** [comment]
Test with my config... It's works

title.strings: (in language directory)
```
"Brainstorming" = "Let Your Ideas Grow";
"Organizing" = "Think Content, Not Layout";
"Sharing" = "Spread Your Ideas Easily";
"Styling" = "Say It Your Way";
```

keyword.strings: (in language directory)
```
"Brainstorming" = "BRAINSTORMING";
"Organizing" = "ORGANIZING";
"Sharing" = "SHARING";
"Styling" = "STYLING";
```

Framefile.json
```
{
    "default": {
        "keyword": {
            "fonts": [
                      {
                      "font": "./fonts/SyrCOMAntioch.otf",
                      "supported": ["fr-FR"]
                      }
                      ]
        },
        "title": {
            "fonts": [
                      {
                      "font": "./fonts/SyrCOMAntioch.otf",
                      "supported": ["fr-FR"]
                      }
                      ],
            "color": "#545454"
        },
        "background": "./background.jpg",
        "padding": 50
    },
    
    "data": [
             {
             "filter": "Brainstorming",
             "keyword": {
             "color": "#d21559"
             }
             },
             {
             "filter": "Organizing",
             "keyword": {
             "color": "#feb909"
             }
             },
             {
             "filter": "Sharing",
             "keyword": {
             "color": "#aa4dbc"
             }
             },
             {
             "filter": "Styling",
             "keyword": {
             "color": "#31bb48"
             }
             }
             ]
}
```

**Comment by olutsenko** [comment]
@skrew I have the same output with your configuration. Do I have to follow some file-naming format for the screenshots to match them with data in .strings file?

**Comment by skrew** [comment]
@olutsenko yes, eg: i would use `1_iphone6_Brainstorming.png` for the first in example. Tested, it works.

**Comment by kcandr** [comment]
@olutsenko Are your ```.strings``` files encoded with UTF-16? Do you saw https://github.com/fastlane/frameit/issues/32?

**Comment by bartl-git** [comment]
Hi. I got the same problem.
Strings files are utf-16 encoded.
Did anyone solve this?

**Comment by chinnawatp** [comment]
For anyone having this eror 
```Could not get title for screenshot " ". Please provide one in your Framefile.json"```
My solution is to put filed "text" in  "title":{} Framefile.json   

*Example
Framefile.json
```
 "title": {
      "text" : "My very long title\nwith line break",   
      "fonts": [
        {
          "font": "./fonts/DB HELVETHAICAMON X MED V3.2.TTF",
          "supported": ["de-DE", "en-US", "es-ES", "fr-FR", "it-IT", "nl-NL", "sv-SE", "pt-BR"]
        }
      ],
      "color": "#545454"
    }
```

**Comment by soheil** [comment]
Here is a sample for anyone else stuck:

```
{
  "default": {
    "keyword": {
      "font": "./Roboto-Regular.otf"
    },
    "title": {
      "font": "./Roboto-Bold.otf",
      "color": "#545454"
    },
    "background": "./background.jpg",
    "padding": 50
  },
  "data": [
    {
      "filter": "List",
      "keyword": {
        "color": "#d21559"
      },
      "title": {
        "text": "nice"
      }
    }
  ]
}
```

**Comment by zkirill** [comment]
Had trouble with Xcode not saving in UTF-16 so I used TextWrangler. The setting is located on the status bar.

![screen shot 2015-12-02 at 3 12 43 pm](https://cloud.githubusercontent.com/assets/205733/11547214/318e7d68-9907-11e5-96d6-fe269490edfd.png)

**Comment by juliengomes** [comment]
I spent the last 4 hours trying to make it work... and it still doesn't !
This is a great tool, but guys please provide the minimum vital doc please, it's a real PITA !

**Comment by KrauseFx** [comment]
@juliengomes I'm more than happy to merge a pull request improving the docs so they're easier to understand. Many users got a working setup using the example files and documentation.

**Comment by jeeftor** [comment]
Maybe we could just link to this issue - if i get a chance i'll do ti.

**Comment by Rico99** [comment]
@olutsenko For what it's worth, I ran into the same issue today and finally figured it out.

If you are using localized screenshots, you must **place the screenshots into the language folder** (e.g. en-US) that contains the .strings files.

Your test screenshots Organizing.png and Brainstorming.png are at the top level, but they have to go into the *en-US* folder (along with the .stings files).

**Comment by hunterleebrown** [comment]
@Rico99 THANK YOU! I had to place the screenshots in the language folder!  doh!   I hadn't taken the screenshots, my colleague did... but I see now "en-US" in their file name.   Thanks again!
