### ISSUE TITLE
Feature request: Frame apple watch screens

### ISSUE THREAD

**Issue by yinkou** [fastlane/frameit#52]
It's not for the app store but it is useful to quickly put designs and concepts into a nice device for presentations or whatever.

**Comment by JagCesar** [comment]
@yinkou [Here are some high quality apple watch frames](https://dribbble.com/shots/1914277-Apple-Watch-Bezels-For-Bezel), they are made by @maxrudberg

And if you have an app you want to see in the frames mentioned above you can use those frames together with [Bezel](http://infinitapps.com/bezel/)

**Comment by yinkou** [comment]
Thank you, i know what a can do and also that there a great illustrator/photoshop/sketch mockups out there.
But what i want is support for apple watch screen in frameit.
I guess my austrian friend here is quite busy with twitter right now. ;)

**Comment by KrauseFx** [comment]
Do you know if Apple approved apps with screenshots with framed apple watch screenshots?

**Comment by yinkou** [comment]
No, i haven't tried it out yet.
I mainly need it for design and presentation purposes. That's also a thing you toolchain is used for. ;)
