### ISSUE TITLE
Followed instructions, copied example folders as is but got the title not found problem still

### ISSUE THREAD

**Issue by tinyhappysteps** [fastlane/frameit#60]
Like the other posters (same error message).  Didn't edit the files at all and made sure all the files and folders including custom fonts were there.  Any suggestions?

ps - if anyone has a working folder that would be MUCH appreciated

**Comment by aabulkhairov** [comment]
Me too with this problem

**Comment by vpolouchkine** [comment]
Can you please post the full output and your Framefile.json?
