### ISSUE TITLE
Is there a way to show my whole screenshot?

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/frameit#67]
the bottom row of my app is particularly important.

In many of the framed screenshots, they drop below the page and the bottom of the app (bottom toolbar) is hidden.

Is there a way I can say something along the lines of 'push the device up by X pixels'
Or perhaps 'show full screen'

There certainly seems to be space to spare where the title is...

 
![ipadretina-01controlsscreen_framed](https://cloud.githubusercontent.com/assets/586910/11016943/9416032c-8587-11e5-8589-0d793633f9e2.png)

![ipadretina-01controlsscreen](https://cloud.githubusercontent.com/assets/586910/11016944/9f45177e-8587-11e5-9e47-a2d8d5eb4d28.png)

**Comment by KrauseFx** [comment]
Sorry, that's not possible with `frameit` now :cry:

**Comment by ConfusedVorlon** [comment]
Ok - now there is...
https://github.com/fastlane/frameit/pull/68
