### ISSUE TITLE
Unsupported screen size when framing for Mac

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/frameit#69]
My mac screenshots are 646*907
This should work perfectly with my background - but frameit isn't happy.

     [15:42:33]: Unsupported screen size [646, 907] for path './screenshots/en-US/1screen-ios.png'

is there a way to say 'this is for Mac, so just use whatever size I give  you' ?

**Comment by ConfusedVorlon** [comment]
to illustrate what I'm trying to achieve - this is the result using photoshop to resize the original screenshot with transparent padding so that it appears to be a valid size

![1screen-ios-sized_framed](https://cloud.githubusercontent.com/assets/586910/11151484/3d616ad8-8a25-11e5-97ba-77687573d106.png)

**Comment by aabulkhairov** [comment]
Have you resolved this? I'm stuck on this issue too! My background image is 1440x900, initial screen capture is also 1440x900, while the frame inside background macbook screen is 922x576.
Here's what i get:

![1-slide1_framed](https://cloud.githubusercontent.com/assets/1159964/13318771/bc1f5c8c-dbcd-11e5-98b6-32b72b9b0ff7.png)

Please someone help. How to define desired screen capture size?

**Comment by vpolouchkine** [comment]
`frameit` currently supports iPhone 6 Plus, iPhone 6, iPhone 5s and iPad mini. 

We'll see what we can do in a future release. I’ll reopen this ticket and keep you updated when we get a chance to revisit this, stay tuned :+1: If you want to tackle this yourself, check out the [countdown](https://github.com/fastlane/countdown) repo to learn how to contribute to `fastlane`.

**Comment by ConfusedVorlon** [comment]
the description on the front page of this repo says that it supports Mac OS including providing instructions in the Mac separate section. ```With frameit 2.0 it's possible to also frame Mac OS X Application screenshots.```

**Comment by vpolouchkine** [comment]
Ah, yes, you're right.
