### ISSUE TITLE
Suggestion: Generate iPad and iPhone combo

### ISSUE THREAD

**Issue by AndreasAppInMed** [fastlane/frameit#73]
Is it possible to setup frameit to support the "iPad Air 2 and iPhone 6s" combo (from https://developer.apple.com/app-store/marketing/guidelines/#images)? If so, in my case I would prefer both frames in portrait. I understand that there a number of possible combinations of iPad+iPhone, but some kind of settings file as Framefile.json could work.

**Comment by KrauseFx** [comment]
Sorry, that's not possible with `frameit`
