### ISSUE TITLE
Option to limit Maximum font size

### ISSUE THREAD

**Issue by Tibbs** [fastlane/frameit#75]
The font size can be huge for short titles. It makes it look especially bad if there are longer titles for the same device.
It also changes bottom offset, so it makes the screenshots misaligned.

It would be a good idea to limit the font size, maybe with a sale factor similar to UILabel's minimumScaleFactor.

I tried to add extra spacing to the title, but frameit removes all white space.

**Comment by siburb** [comment]
+1. Similar to #76 . This would possibly be solved by forcing the font to be the same size across all of the screenshots for a particular device. Therefore will only be as large as the longest title will allow.
