### ISSUE TITLE
Same font size among one device

### ISSUE THREAD

**Issue by alexmarktl** [fastlane/frameit#76]
It would be great if there would be an option that calculates the font size among all 5 screens for one device so that it would be the same (if possible) on all 5 framed screens.

**Comment by siburb** [comment]
Surely this is essential? The current font sizes are all over the place.

Perhaps along with "titleHeight", we can get more uniform results across one particular device?

**Comment by alexmarktl** [comment]
Agreed. titleHeight may be a better solution.

**Comment by siburb** [comment]
I think a combination of titleHeight and **and** option to force the font to be the same size for a particular device would  be a great solution.

Some people like to have the some of the bottom chrome of the iPhone appearing at the bottom of the screenshots, whereas some people prefer to have the bottom of the screen at the bottom of the screenshots - titleHeight will allow this to be configured, and it will also allow us to make sure all of the devices are in line across all screenshots.

An option to make sure the font it the same size across screenshots on a particular device would mean it sits nicely and doesn't have to "fill" the available space.

**Comment by felixLam** [comment]
+1

**Comment by donnywals** [comment]
+1, is somebody working on this?
