### ISSUE TITLE
Strange scaling issue

### ISSUE THREAD

**Issue by plaetzchen** [fastlane/frameit#80]
Hi there,

After updating to 1.2.2 I changed the padding to 0x0 and now I get this strangely scaled frames:

Before:
![500x500bb](https://cloud.githubusercontent.com/assets/365135/11566670/b269c686-99e3-11e5-81c8-96756baa7b8b.jpg)

After:
![iphone5-0-news_framed](https://cloud.githubusercontent.com/assets/365135/11566678/ba9ef22c-99e3-11e5-810f-6da3aadc23c4.png)

**Comment by plaetzchen** [comment]
The before one is pulled out of iTC so it's smaller in pixels (thats OK) The scaled phone is what bothers me.

**Comment by KrauseFx** [comment]
@plaetzchen and it worked with `1.2.1`? Did you change anything in your configuration?
