### ISSUE TITLE
Incorrect baseline alignment between keyword and title.

### ISSUE THREAD

**Issue by MartinRogalla** [fastlane/frameit#82]
When I run frameit, the baseline of the keyword and title is misaligned(see image below). How do I fix this? The configuration used is the same as the one used by the MindNode example with modification to the font and text-colors.

*Please ignore the text as it is just a filler. I removed the screenshot from the image.*

![iphone6splus](https://cloud.githubusercontent.com/assets/1066157/11615128/985b92c0-9c58-11e5-9af5-265694207c84.png)

**Comment by MartinRogalla** [comment]
After looking into it a bit more, the "keyword" and "title" are separate images, which are trimmed from their whitespace and are then top aligned, causing a shift for all the text that has a different height.
Exact location of the trimming in the code:
https://github.com/fastlane/frameit/blob/master/lib/frameit/editor.rb#L251

An extreme example for this is when using the following values: **keyword** "*_*" and **title** "*Example*"

This results in an image with the underscore top aligned as is shown in the image below:
![iphone5-1launch_framed](https://cloud.githubusercontent.com/assets/1066157/11615862/355bf7aa-9c6c-11e5-90ae-276d30250adc.png)

**Comment by KrauseFx** [comment]
Oh wow, nice catch!

**Comment by felixLam** [comment]
I encountered the same issue. I started looking into the code, but I don't see an easy fix with the current logic using imagemagick for two separate labels. Would love to see this fixed, as for now we can only use the title.
