### ISSUE TITLE
Option to Disable white space trimming 

### ISSUE THREAD

**Issue by Tibbs** [fastlane/frameit#85]
I tried to control the title font size and add dummy second lines but frameit removes all whitecap at the beginning and the end of the title.

If it didn't I could achieve more or less uniform title font size by playing with white spaces

For example titles below should produce similar font sizes
Title1 = "           short title           " 
Title2 = "Much much longer title"
Title3 = "    Very long line title   \n  for an example here "

**Comment by felixLam** [comment]
This might be the same issue as https://github.com/fastlane/frameit/issues/76

**Comment by Tibbs** [comment]
Yes, IT is the same issue. But this could be done much easier by disabling only one line. Optimal Font sizes can be wastly different for each device. Whereas spaces scale automatically

**Comment by Rico99** [comment]
+1 Ran into the same issue. The font size on the iPad screenshots is way too large (I use only short titles) and I was looking for a way to decrease the font size. Adding spaces in front and at the end could be a simple way to "set" the font size.

Of course, being able to set a maximum font size as described in #75 would work as well.
