### ISSUE TITLE
Is there the ability to have landscape backgrounds with portrait device frames?

### ISSUE THREAD

**Issue by cameroncooke** [fastlane/frameit#96]
Is there an option that would allow the mixture of portrait device screenshots to be displayed over a landscape background and visa-versa?

So we could achieve the following example:

![Example Image](https://is1-ssl.mzstatic.com/image/thumb/Purple69/v4/9c/e7/eb/9ce7eb1b-0c5d-9467-be5e-869b578f5155/pr_source.png/0x0ss.jpg)

**Comment by KrauseFx** [comment]
Sorry, that's not possible currently

**Comment by cameroncooke** [comment]
I'm currently working on adding this feature. I've fork s the repro and
have managed to achieve this effect while preserving original
functionality. It's my first Ruby code so need some feed back ideally. The
approach me and a colleague have taken is to allow mixed orientations
between the background image and the frame. For example if you specify an
iPad andscape background image and the frame is portrait iPad it will allow
this instead of resizing background into portrait as it currently does.

There is still some more work to do with iPhone as while it looks great for
iPad frames not so hot on iPhone but I foresee this just being down to the
user choosing the right backgrounds and making sensible choices. Clearly
iPhone frame in landscape on a portrait background probably won't look
amazing. But I think we can tweak this.

Fork: https://github.com/brightec/frameit

I would be interested on your feedback on this?

Thanks.

**Comment by cameroncooke** [comment]
Did you get a chance to have a look at what we've done? Just would be interested to see if it has an value and whether we should continue it further?
